# Operators
### An operator is a symbol that tells the compiler to perform specific mathematical or logical manipulations.

## Types of operators
- #### Arithmetic Operators
- #### Relational Operators
- #### Logical Operators
- #### Assignment Operators
- #### Miscellaneous Operators

### Arithmetic Operators
 - Addition
 - Subtraction
 - Multiplication
 - Division
 - Exponent
 - Modulus (Remainder from division)
 - Integer Division

In [15]:
# Addition
v  <- c (2, 6i, 4)
l  <- c (4, 2i, 3)
print (v+l)

[1] 6+0i 0+8i 7+0i


**If the vectors are of different lengths, the shorter vector will be recycled to match the length of the longer vector.**

![image](https://datascienceparichay.com/wp-content/uploads/2022/04/R-add-two-vectors-thumbnail.png)

In [6]:
# Example of adding with vectors of different lenght
v  <- c (2, 6i, 4, 9, 2)
l  <- c (4, 2i, 3)
print (v+l)

Warning message in v + l:
“longer object length is not a multiple of shorter object length”


[1]  6+0i  0+8i  7+0i 13+0i  2+2i


In [9]:
# Subtraction
l  <- c (4,6,8)
m  <- c (9,5,6)
print (l-m)

[1] -5  1  2


In [11]:
# Multiplication
a  <- c (3, 2)
b  <- c (4,6)
print (a*b)

[1] 12 12


In [12]:
# Division
v <- c( 2,5.5,6)
t <- c(8, 3, 4)
print(v/t)

[1] 0.250000 1.833333 1.500000


In [13]:
# Exponent
l  <-  (2)
t  <- (3)
print (l*t)

[1] 6


### Relational operators

#### Greater than
3 > 2
#### Less than
3 < 2
#### Equal to
3 == 2
#### Not equal to
3 != 2
#### Greater than or equal to
3 >= 2
#### Less than or equal to
3 <= 2

### Logical operators
*All numbers greater than 1 are considered as logical value **TRUE***

- AND (&)
- OR (|)
- NOT (!)

*The logical operator && and || considers only the first element of the vectors and give a vector of single element as output*

- **&&** Called Logical AND operator
Takes first element of both the vectors and gives the TRUE only if both are TRUE

- **||** Called Logical OR operator
Takes first element of both the vectors and gives the TRUE if one of them is TRUE

### Assignment Operators
*These operators are used to assign values to vectors*

- #### Called Left Assignment

**<−**   
**=**   
**<<−**

- #### Called Right Assignment

**->**     
**->>**

### Miscellanous operators
These operators are used to manipulate data:

- **:**	Creates a series of numbers in a sequence
- **%in%**	Find out if an element belongs to a vector
- **%*%**	Matrix Multiplication

In [16]:
# Example for :

l <- (6:12)
print (l)

[1]  6  7  8  9 10 11 12


In [17]:
# Example for %in%

l1  <- 6
l2  <- 2
l  <- (6:12)
print (l1 %in% l)
print (l2 %in% l)

[1] TRUE
[1] FALSE


#### Example for %*%

This operator is used to multiply a matrix with its transpose

The transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by AT

![image](https://static.todamateria.com.br/upload/ma/tr/matriztransposta7.jpg?auto_optimize=low)

In [18]:
M = matrix( c(2,6,5,1,10,4), nrow = 2,ncol = 3,byrow = TRUE)
t = M %*% t(M)
print(t)

     [,1] [,2]
[1,]   65   82
[2,]   82  117


In [24]:
### Explaning

# Original matrix

M = matrix( c(2,6,5,1,10,4), nrow = 3,ncol = 2,byrow = TRUE)
print (M)

# Transpose matrix
T = matrix( c(2,5,10,6,1,4), nrow = 2,ncol = 3,byrow = TRUE)
print (T)

     [,1] [,2]
[1,]    2    6
[2,]    5    1
[3,]   10    4
     [,1] [,2] [,3]
[1,]    2    5   10
[2,]    6    1    4


In [25]:
# With the %*% command, the matrix will be multiplied with transpose matrix